title: David Sierra Porta
description: Como lo veo. Algunos pasamos la vida concentrados en algo que nos emociona, nos alimenta y nos inspira, y hacemos que toda esa vida gire en torno a esa emoción. Hacer con las manos, luchar y hacer de esa lucha la razón de las alegrías, encontrando en el camino satisfacción y realización. Como ese pescador que sale cada madrugada, cada día, y cada noche a congraciarse con la vida, haciendo un cayo por cada hazaña y lucha. Así lanzo las redes cada día...
#container: large
logo: 33108113860_c247cf2e65_b.jpg
show_downloads: true
#google_analytics:
#theme: jekyll-theme-modernist
#theme: jekyll-theme-architect
#theme: jekyll-theme-leap-day
#theme: jekyll-theme-tactile
theme: jekyll-theme-minimal
#theme: minima


