title: Mathematics for Machine Learning
email: feedback@mml-book.com
description: >- # this means to ignore newlines until "baseurl:"
  Companion webpage to the book "Mathematics for Machine Learning".
  Copyright 2019 by Marc Peter Deisenroth, A Aldo Faisal, and Cheng Soon Ong. To be published by Cambridge University Press.
theme: jekyll-theme-modernist
