title: David Sierra Porta
description: Bienvenidos a mi página personal. Para mí, lo más importante es poder aprender cosas todos los días 
y progresar. Realmente disfruto mi trabajo, ya que interactuo constantemente con investigadores colegas.
Otro aspecto del trabajo que realmente me gusta es la necesidad de explicar nuestro trabajo en términos simples a 
los no expertos. Me encanta abordar problemas complicados y tratar de encontrar soluciones originales para 
abordarlos. Y no hay nada rutinario al respecto, aprendemos cosas nuevas todo el tiempo y los problemas en los que 
trabajamos son muy variados. No todos hacemos lo mismo. Pero eso no significa que trabajemos solos. 
#theme: jekyll-theme-modernist
