title: "It is my Blog"
author: "D. Sierra Porta"
description: "How I see it. Some of us spend our lives focused on something that excites, nourishes and inspires us, and we 
make that whole life revolve around that emotion. Doing with our hands, struggling and making that struggle the reason for 
our joys, finding satisfaction and fulfillment along the way. Like that fisherman who goes out every morning, every day, and 
every night to ingratiate himself with life, his hands tanned by the substance of his work, his back torn by the sun that gives 
him life and his shoulders cracked from the weight of his labors, hands with bruises from every feat and struggle, but at the 
same time, his heart and soul full of deep pride and happiness. This is how I cast my nets every day..."
email: "sierraporta@gmail.com"
github-username: "sierraporta"
#container: large
show_downloads: true
#google_analytics:
#theme: jekyll-theme-modernist
#theme: jekyll-theme-architect
#theme: jekyll-theme-leap-day
#theme: jekyll-theme-tactile
theme: jekyll-theme-minimal
#theme: minima
